"""init

Revision ID: 65846f6edb6f
Revises: 
Create Date: 2021-10-17 18:44:21.037807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65846f6edb6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=300), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inbox')
    # ### end Alembic commands ###
